use_frameworks!
inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://gitee.com/misterzhouwei/MyRepo.git'

platform :ios, '8.0'

target 'ZWOCComponent' do
  pod 'MBProgressHUD'
  pod 'YYKit'
  pod 'MJRefresh'
  pod 'SDWebImage'
  pod 'TZImagePickerController'
  pod 'Masonry'
  pod 'MJExtension'
  pod 'AFNetworking'
  pod 'ZWBaseToolsComponent', '0.0.1'
  pod 'ZWBaseModulesComponent', '0.0.1'
  
end
